#!/usr/bin/env bash
# replan-on-tag.sh — fires on SessionStart + Stop. Replaces the v0.1
# replan-on-ship.sh. Detects when a new v* tag has been pushed since
# the last marker, scaffolds the next version's plan at
# docs/process/plans/v<NEXT>-plan.md, and injects context telling Claude
# Code to read it and execute. Zero pause — if the plan file already
# exists, just point Claude at it.
#
# Idempotent. Marker advanced via .claude/hooks/mark-replanned.sh after
# Claude has read the new plan and committed at least one step.
#
# Plan-file naming: v<MAJOR>.<MINOR>-plan.md (drops patch — minor bumps
# get a fresh plan; patch bumps reuse the active plan with a CHANGELOG
# entry).

set -euo pipefail

repo="${CLAUDE_PROJECT_DIR:-$(pwd)}"
marker="$repo/.claude/.last-shipped-tag"
plans_dir="$repo/docs/process/plans"

mkdir -p "$repo/.claude" "$plans_dir"
touch "$marker"
last_seen="$(cat "$marker")"

# Only act inside a git repo.
if ! git -C "$repo" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  exit 0
fi

# Pick the most recent v* tag by version sort (not creation date — a
# patch tag pushed late shouldn't override a minor tag pushed earlier).
latest_tag="$(git -C "$repo" tag -l 'v*' --sort=-v:refname | head -n1 || true)"

if [ -z "$latest_tag" ]; then
  exit 0
fi

if [ "$latest_tag" = "$last_seen" ]; then
  exit 0
fi

# Strip 'v' prefix, parse semver. Tolerant of pre-release suffixes
# (e.g. v0.2.0-beta.1).
version="${latest_tag#v}"
core="${version%%-*}"
IFS='.' read -r major minor patch <<<"$core"
major="${major:-0}"
minor="${minor:-0}"
patch="${patch:-0}"

# Next minor by default. If the shipped tag is a patch (vX.Y.Z, Z>0),
# there's no replan — patches reuse the active plan.
if [ "${patch}" != "0" ]; then
  exit 0
fi

next_major="$major"
next_minor="$((minor + 1))"
next_version="v${next_major}.${next_minor}"
plan_file="$plans_dir/${next_version}-plan.md"

# Detect channel from event payload to scope additionalContext key.
event_name="SessionStart"
if [ -n "${CLAUDE_HOOK_EVENT:-}" ]; then
  event_name="$CLAUDE_HOOK_EVENT"
fi

# If the plan file doesn't exist yet, scaffold it. Claude fills it in
# during the first session of the new cycle.
if [ ! -f "$plan_file" ]; then
  cat >"$plan_file" <<EOF
# Sojourn ${next_version} Plan

Status: **draft — autoplan, untriaged**. Generated by
\`.claude/hooks/replan-on-tag.sh\` on shipment of \`${latest_tag}\`.

Read \`docs/process/plans/${last_seen:-(prior plan)}.md\`,
\`CHANGELOG.md\`, the latest ADRs, and \`lessons.md\` (entries since the
last ship). Then rewrite this file in the same shape as the prior plan:

- "What this is" — one paragraph on the next chunk of work.
- "Why (one paragraph each)" — for any new pivots.
- "Hard decisions (locked)" — anything carried forward + new locks.
- "ADRs to write, amend, or reject" — what's new.
- "Docs purge / fold" — anything stale.
- "Source code: file-by-file changes" — Add / Delete / Rewrite.
- "Execution order" — ordered steps with exit criteria each.
- "Acceptance criteria for ${next_version}" — release gate.
- "Council triggers (recap)" — same as prior unless deliberately changed.
- "Open questions for v$((next_minor + 1))".
- "Don't" — explicit anti-patterns surfaced this cycle.

Open questions carried over from the prior plan are the priority. Cross
them off as they're resolved or punted. After this file is rewritten and
the first execution-step commit lands, run:

\`\`\`sh
bash .claude/hooks/mark-replanned.sh ${latest_tag}
\`\`\`

to advance the marker. Until then, every session start re-prompts.

## Likely scope (delete this section once the plan is rewritten)

(Carry-over from the prior cycle's "Open questions for ${next_version}".)
EOF
fi

cat <<EOF
{
  "hookSpecificOutput": {
    "hookEventName": "${event_name}",
    "additionalContext": "Sojourn shipped ${latest_tag}. The next-version plan scaffold lives at ${plan_file}. Read the prior plan, the ADRs added since, the CHANGELOG since ${last_seen:-the start of the project}, and lessons.md entries since ${last_seen:-the start of the project}. Rewrite ${plan_file} per the template inside it. Then start executing top-to-bottom. After the first execution-step commit lands, run: bash .claude/hooks/mark-replanned.sh ${latest_tag} . Do not pause for confirmation — autoplan and proceed per CLAUDE.md."
  }
}
EOF
