// Sojourn — MachinesPane

import SwiftUI

struct MachinesPane: View {
  private struct Machine: Identifiable {
    let id: String
    let host: String
    let model: String
    let os: String
    let lastSync: String
    let writer: Bool
    let pkgs: Int
    let role: String
  }

  private var fleet: [Machine] {
    [
      .init(id: "work-mbp", host: "mbp16-acme.local", model: "MacBook Pro 16\" · M3 Max", os: "14.5 Sonoma", lastSync: "2h ago", writer: true, pkgs: 184, role: "PRIMARY"),
      .init(id: "personal-mini", host: "mini-home.local", model: "Mac mini · M4", os: "15.1 Sequoia", lastSync: "2d ago", writer: false, pkgs: 142, role: "PERSONAL"),
      .init(id: "ci-runner", host: "gh-runner-arm-04", model: "M2 in a closet", os: "14.2 Sonoma", lastSync: "6h ago", writer: false, pkgs: 67, role: "EPHEMERAL")
    ]
  }

  var body: some View {
    ScrollView {
      VStack(alignment: .leading, spacing: 18) {
        EyebrowLabel(text: "3 MACHINES · 1 ACTIVE WRITER · COOPERATIVE LOCK")
          .padding(.top, 8)
        Text("YOUR FLEET")
          .font(.bzrStencil(size: 30, weight: .heavy))
          .foregroundStyle(Color.txtPrimary)
        Text("One active writer at a time. Pull before push. The lock is a hint git doesn't enforce — it catches the 95% case of a forgotten pull. Per-machine overrides via {{ if eq .chezmoi.hostname \"...\" }} are generated by the form.")
          .font(.bzrBody(size: 13))
          .foregroundStyle(Color.txtSecondary)
          .frame(maxWidth: 64 * 9, alignment: .leading)

        let cols = [
          GridItem(.flexible(minimum: 320), spacing: 12),
          GridItem(.flexible(minimum: 320), spacing: 12),
          GridItem(.flexible(minimum: 320), spacing: 12)
        ]
        LazyVGrid(columns: cols, spacing: 12) {
          ForEach(fleet) { m in
            machineCard(m)
          }
        }

        Text("Repo · git@github.com:you/my-mac.git")
          .font(.bzrDetailH2)
          .foregroundStyle(Color.txtPrimary)
          .padding(.top, 6)

        BzrCard {
          BzrCodeBlock(text: """
            my-mac/
            ├── Brewfile.common               // brew bundle dump
            ├── dotfiles/                     // chezmoi source dir
            │   ├── dot_zshrc.tmpl
            │   ├── dot_gitconfig.tmpl
            │   └── private_dot_ssh/encrypted_id_ed25519.age
            ├── preferences/                  // XML plist per domain
            │   ├── com.googlecode.iterm2.plist
            │   └── com.apple.dock.plist
            └── .sojourn/
                ├── machines/work-mbp.toml
                ├── active.toml               // writer = "work-mbp"
                ├── version.toml
                └── backups/                  // pre-op snapshots, 30d
            """)
        }
      }
      .padding(28)
      .frame(maxWidth: .infinity, alignment: .leading)
    }
    .accessibilityIdentifier("pane.machines")
  }

  @ViewBuilder
  private func machineCard(_ m: Machine) -> some View {
    VStack(alignment: .leading, spacing: 0) {
      VStack(alignment: .leading, spacing: 6) {
        HStack(spacing: 8) {
          StatusDot(kind: m.writer ? .lime : .ok)
          Text(m.id.uppercased())
            .font(.bzrStencil(size: 18, weight: .heavy))
            .tracking(1.6)
            .foregroundStyle(Color.txtPrimary)
          Spacer()
          Text(m.role)
            .font(.bzrMono(size: 9, weight: .semibold))
            .tracking(1.6)
            .foregroundStyle(Color.txtTertiary)
        }
        Text(m.host)
          .font(.bzrMono(size: 10))
          .foregroundStyle(Color.txtTertiary)
      }
      .padding(.horizontal, 16)
      .padding(.vertical, 14)
      .frame(maxWidth: .infinity, alignment: .leading)
      .background(m.writer ? Color.bzrLime.opacity(0.10) : Color.white.opacity(0.02))
      .overlay(
        Rectangle()
          .fill(m.writer ? Color.bzrLime.opacity(0.30) : Color.hairline)
          .frame(height: 0.5),
        alignment: .bottom
      )

      VStack(alignment: .leading, spacing: 6) {
        machineRow("Model", m.model)
        machineRow("OS", m.os)
        machineRow("Packages", "\(m.pkgs)", lime: true)
        machineRow("Last sync", m.lastSync)
        HStack(spacing: 6) {
          Text("Writer")
            .font(.bzrBody(size: 12))
            .foregroundStyle(Color.txtTertiary)
            .frame(width: 80, alignment: .leading)
          if m.writer {
            BzrBadge(text: "ACTIVE", kind: .lime)
          } else {
            BzrBadge(text: "TAKE LOCK", kind: .mute)
          }
          Spacer()
        }
        .padding(.top, 4)

        HStack(spacing: 8) {
          Button {} label: {
            HStack(spacing: 4) { Image(systemName: "terminal").font(.system(size: 11)); Text("Open in iTerm") }
          }
          .buttonStyle(GlassCapsuleButtonStyle())
          if m.writer {
            Button {} label: { Image(systemName: "gearshape").font(.system(size: 11)) }
              .buttonStyle(GlassGhostButtonStyle())
          }
          Spacer()
        }
        .padding(.top, 8)
      }
      .padding(.horizontal, 16)
      .padding(.vertical, 14)
    }
    .background(
      RoundedRectangle(cornerRadius: BzrRadius.card, style: .continuous)
        .fill(Color.glassCard)
        .overlay(
          RoundedRectangle(cornerRadius: BzrRadius.card, style: .continuous)
            .stroke(Color.hairlineStrong, lineWidth: 0.5)
        )
    )
    .clipShape(RoundedRectangle(cornerRadius: BzrRadius.card, style: .continuous))
  }

  @ViewBuilder
  private func machineRow(_ label: String, _ value: String, lime: Bool = false) -> some View {
    HStack {
      Text(label)
        .font(.bzrBody(size: 12))
        .foregroundStyle(Color.txtTertiary)
        .frame(width: 80, alignment: .leading)
      if lime {
        Text(value)
          .font(.bzrMono(size: 12, weight: .semibold))
          .foregroundStyle(Color.bzrLime)
      } else {
        Text(value)
          .font(.bzrBody(size: 12))
          .foregroundStyle(Color.txtPrimary)
      }
      Spacer()
    }
  }
}
